/*

 FACE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char smiler[] =
{
  0x3C,0x3C,0x7E,0x42,0xFF,0x81,0xFF,0xA5,
  0xDB,0xA5,0xFF,0x99,0x66,0x5A,0x3C,0x3C
};

/* End of FACE.C */
